name = "bunq2ynab"
main = "dist/index.js"
compatibility_date = "2023-10-30"

workers_dev = true

kv_namespaces = [
  { binding = "bunq2ynab", id = "20a325ee35d54fa8b8a0d3563e5e377e" }
]


[build]
command = "bun run build"

[triggers]
crons = [ "8-59/10 * * * *" ]
